export interface Photo {
  src: string;
  caption?: string;
}

export interface Apartment {
  id: string;
  title: string;
  neighborhood: string;
  address: string;
  area: number;
  bedrooms: number;
  bathrooms: number;
  parking: number;
  rent: number;
  condo: number;
  iptu: number;
  total: number;
  phone: string;
  email: string;
  link: string;
  image: string;
  features: string[];
  description: string;
  // Banco de links (pesquisa real, sessão 2026-09-22)
  source?: string;
  zapId?: string;
  condoUnknown?: boolean;
  // Leva dores-consumidor (S001, aditivo — ausente = aluguel, nada quebra)
  transaction?: "aluguel" | "venda";
  salePrice?: number;
  photos?: Photo[];
  floorPlan?: string;
  pets?: string;
  guarantor?: string;
  verifiedAt?: string;
}

// Dados REAIS validados em 22/09/2026 (Zap Imóveis, HTTP 200).
// Filtro: 3+ quartos, vazio/semi, aluguel+condomínio ≤ R$4.500, ≤3,5km da Praça Tiradentes.
// total = aluguel líquido + condomínio + IPTU. Telefones/e-mails mascarados nos portais:
// contato sempre pelo link do anúncio original.
// Simulados originais preservados em data/apartamentos.json (backup).
export const apartments: Apartment[] = [
  {
    id: "zap-aguaverde-castro-123",
    title: "Apartamento com 3 Quartos - Água Verde",
    neighborhood: "Água Verde",
    address: "Rua Castro - Água Verde, Curitiba - PR",
    area: 123,
    bedrooms: 3,
    bathrooms: 2,
    parking: 1,
    rent: 2350,
    condo: 0,
    iptu: 0,
    total: 2350,
    phone: "",
    email: "",
    link: "https://www.zapimoveis.com.br/imovel/aluguel-apartamento-3-quartos-agua-verde-curitiba-pr-123m2-id-2912679822/",
    image: "/imoveis/zap-aguaverde-castro-123.webp",
    photos: [
      { src: "/imoveis/zap-aguaverde-castro-123.webp", caption: "Foto principal" },
      { src: "/imoveis/zap-aguaverde-castro-123/01.webp" },
      { src: "/imoveis/zap-aguaverde-castro-123/02.webp" },
      { src: "/imoveis/zap-aguaverde-castro-123/03.webp" },
      { src: "/imoveis/zap-aguaverde-castro-123/04.webp" },
      { src: "/imoveis/zap-aguaverde-castro-123/05.webp" },
      { src: "/imoveis/zap-aguaverde-castro-123/06.webp" },
      { src: "/imoveis/zap-aguaverde-castro-123/07.webp" },
      { src: "/imoveis/zap-aguaverde-castro-123/08.webp" },
      { src: "/imoveis/zap-aguaverde-castro-123/09.webp" },
      { src: "/imoveis/zap-aguaverde-castro-123/10.webp" },
    ],
    features: ["1 suíte", "Aceita animais", "123m²", "Condomínio a confirmar"],
    description: "Apartamento amplo com 123m² em uma das regiões mais valorizadas da cidade. Aceita animais. Próximo à Maternidade Curitiba, UniFacear, Hospital IPO e Arena da Baixada. Imobiliária Querolar. Condomínio não informado no anúncio — confirmar antes de visitar.",
    source: "Zap Imóveis · Querolar",
    zapId: "2912679822",
    condoUnknown: true,
  },
  {
    id: "zap-aguaverde-raul-90",
    title: "Apartamento com 3 Quartos - Água Verde",
    neighborhood: "Água Verde",
    address: "Rua Doutor Raul Carneiro Filho, 229 - Água Verde, Curitiba - PR",
    area: 90,
    bedrooms: 3,
    bathrooms: 2,
    parking: 1,
    rent: 2500,
    condo: 580,
    iptu: 140,
    total: 3220,
    phone: "",
    email: "",
    link: "https://www.zapimoveis.com.br/imovel/aluguel-apartamento-3-quartos-agua-verde-curitiba-pr-90m2-id-2912831367/",
    image: "/imoveis/zap-aguaverde-raul-90.webp",
    photos: [
      { src: "/imoveis/zap-aguaverde-raul-90.webp", caption: "Foto principal" },
      { src: "/imoveis/zap-aguaverde-raul-90/01.webp" },
      { src: "/imoveis/zap-aguaverde-raul-90/02.webp" },
      { src: "/imoveis/zap-aguaverde-raul-90/03.webp" },
      { src: "/imoveis/zap-aguaverde-raul-90/04.webp" },
      { src: "/imoveis/zap-aguaverde-raul-90/05.webp" },
      { src: "/imoveis/zap-aguaverde-raul-90/06.webp" },
      { src: "/imoveis/zap-aguaverde-raul-90/07.webp" },
      { src: "/imoveis/zap-aguaverde-raul-90/08.webp" },
      { src: "/imoveis/zap-aguaverde-raul-90/09.webp" },
      { src: "/imoveis/zap-aguaverde-raul-90/10.webp" },
    ],
    features: ["3 quartos amplos", "Cozinha com armários", "Depósito", "Aceita animais", "2º andar"],
    description: "03 quartos amplos, sala, copa, cozinha com armários, lavanderia com tanque e aquecedor, depósito, 02 banheiros e 01 vaga para carro grande. A poucos metros da Av. Presidente Kennedy. Nakayoshi Imóveis (Creci 02171-J-PR).",
    source: "Zap Imóveis · Nakayoshi Imóveis",
    zapId: "2912831367",
  },
  {
    id: "zap-ahu-eca-78",
    title: "Apartamento com 3 Quartos - Ahú (Ed. Taiti)",
    neighborhood: "Ahú",
    address: "Rua Eça de Queiroz, 1092 - Ahú, Curitiba - PR",
    area: 78,
    bedrooms: 3,
    bathrooms: 1,
    parking: 1,
    rent: 3000,
    condo: 0,
    iptu: 136,
    total: 3136,
    phone: "",
    email: "",
    link: "https://www.zapimoveis.com.br/imovel/aluguel-apartamento-3-quartos-com-salao-de-festas-ahu-curitiba-pr-78m2-id-2912848342/",
    image: "/imoveis/zap-ahu-eca-78.webp",
    photos: [
      { src: "/imoveis/zap-ahu-eca-78.webp", caption: "Foto principal" },
      { src: "/imoveis/zap-ahu-eca-78/01.webp" },
      { src: "/imoveis/zap-ahu-eca-78/02.webp" },
      { src: "/imoveis/zap-ahu-eca-78/03.webp" },
      { src: "/imoveis/zap-ahu-eca-78/04.webp" },
      { src: "/imoveis/zap-ahu-eca-78/05.webp" },
      { src: "/imoveis/zap-ahu-eca-78/06.webp" },
      { src: "/imoveis/zap-ahu-eca-78/07.webp" },
      { src: "/imoveis/zap-ahu-eca-78/08.webp" },
      { src: "/imoveis/zap-ahu-eca-78/09.webp" },
      { src: "/imoveis/zap-ahu-eca-78/10.webp" },
    ],
    features: ["Sala com sacada", "Cozinha integrada", "Salão de festas", "4º andar", "Condomínio a confirmar"],
    description: "78m² privativos, 03 dormitórios, sala ampla com sacada, cozinha integrada à área de serviço. Edifício Taiti com portaria, salão de festas e churrasqueira. Próximo ao Museu Oscar Niemeyer e Bosque do Papa. Casa Ao Lado Imóveis. Condomínio a confirmar.",
    source: "Zap Imóveis · Casa Ao Lado Imóveis",
    zapId: "2912848342",
    condoUnknown: true,
  },
  {
    id: "zap-centro-comendador-130",
    title: "Apartamento com 3 Quartos - Centro (Ed. Baêta de Faria)",
    neighborhood: "Centro",
    address: "Rua Comendador Araújo, 100 - Centro, Curitiba - PR",
    area: 130,
    bedrooms: 3,
    bathrooms: 2,
    parking: 1,
    rent: 2800,
    condo: 672,
    iptu: 157,
    total: 3629,
    phone: "",
    email: "",
    link: "https://www.zapimoveis.com.br/imovel/aluguel-apartamento-3-quartos-centro-curitiba-pr-130m2-id-2912933319/",
    image: "/imoveis/zap-centro-comendador-130.webp",
    photos: [
      { src: "/imoveis/zap-centro-comendador-130.webp", caption: "Foto principal" },
      { src: "/imoveis/zap-centro-comendador-130/01.webp" },
      { src: "/imoveis/zap-centro-comendador-130/02.webp" },
      { src: "/imoveis/zap-centro-comendador-130/03.webp" },
      { src: "/imoveis/zap-centro-comendador-130/04.webp" },
      { src: "/imoveis/zap-centro-comendador-130/05.webp" },
      { src: "/imoveis/zap-centro-comendador-130/06.webp" },
      { src: "/imoveis/zap-centro-comendador-130/07.webp" },
      { src: "/imoveis/zap-centro-comendador-130/08.webp" },
      { src: "/imoveis/zap-centro-comendador-130/09.webp" },
      { src: "/imoveis/zap-centro-comendador-130/10.webp" },
    ],
    features: ["130m²", "Piso em madeira", "Cozinha planejada", "7º andar com elevador", "Ótimo preço"],
    description: "Sala para 2 ambientes com piso em madeira, cozinha com armários planejados, 3 dormitórios amplos e 1 vaga. Próximo à Praça Osório e Av. Vicente Machado. Casa Prates Imóveis — sem fiador, seguro fiança a partir de 10% do aluguel.",
    source: "Zap Imóveis · Casa Prates Imóveis",
    zapId: "2912933319",
  },
  {
    id: "zap-centro-bufren-96",
    title: "Apartamento com 3 Quartos - Centro",
    neighborhood: "Centro",
    address: "Rua Alfredo Bufren, 285 - Centro, Curitiba - PR",
    area: 96,
    bedrooms: 3,
    bathrooms: 2,
    parking: 0,
    rent: 2600,
    condo: 750,
    iptu: 155,
    total: 3505,
    phone: "",
    email: "",
    link: "https://www.zapimoveis.com.br/imovel/aluguel-apartamento-3-quartos-centro-curitiba-pr-96m2-id-2913256057/",
    image: "/imoveis/zap-centro-bufren-96.webp",
    photos: [
      { src: "/imoveis/zap-centro-bufren-96.webp", caption: "Foto principal" },
      { src: "/imoveis/zap-centro-bufren-96/01.webp" },
      { src: "/imoveis/zap-centro-bufren-96/02.webp" },
      { src: "/imoveis/zap-centro-bufren-96/03.webp" },
      { src: "/imoveis/zap-centro-bufren-96/04.webp" },
      { src: "/imoveis/zap-centro-bufren-96/05.webp" },
      { src: "/imoveis/zap-centro-bufren-96/06.webp" },
      { src: "/imoveis/zap-centro-bufren-96/07.webp" },
      { src: "/imoveis/zap-centro-bufren-96/08.webp" },
      { src: "/imoveis/zap-centro-bufren-96/09.webp" },
      { src: "/imoveis/zap-centro-bufren-96/10.webp" },
    ],
    features: ["19º andar", "Dormitório de serviço", "SEM GARAGEM", "Próx. Praça Santos Andrade"],
    description: "3 dormitórios, sala para 2 ambientes, cozinha, banheiro social, lavanderia e dormitório com banheiro de serviço. Junto à Praça Santos Andrade e UFPR. Osvaldo Nakamura. Atenção: sem vaga de garagem.",
    source: "Zap Imóveis · Osvaldo Nakamura",
    zapId: "2913256057",
  },
  {
    id: "zap-juveve-goulin-66",
    title: "Apartamento com 3 Quartos - Juvevê (reformado)",
    neighborhood: "Juvevê",
    address: "Rua Doutor Goulin, 1226 - Juvevê, Curitiba - PR",
    area: 66,
    bedrooms: 3,
    bathrooms: 2,
    parking: 1,
    rent: 3600,
    condo: 487,
    iptu: 87,
    total: 4174,
    phone: "",
    email: "",
    link: "https://www.zapimoveis.com.br/imovel/aluguel-apartamento-3-quartos-com-playground-juveve-curitiba-pr-66m2-id-2909577516/",
    image: "/imoveis/zap-juveve-goulin-66.webp",
    photos: [
      { src: "/imoveis/zap-juveve-goulin-66.webp", caption: "Foto principal" },
      { src: "/imoveis/zap-juveve-goulin-66/01.webp" },
      { src: "/imoveis/zap-juveve-goulin-66/02.webp" },
      { src: "/imoveis/zap-juveve-goulin-66/03.webp" },
      { src: "/imoveis/zap-juveve-goulin-66/04.webp" },
      { src: "/imoveis/zap-juveve-goulin-66/05.webp" },
      { src: "/imoveis/zap-juveve-goulin-66/06.webp" },
      { src: "/imoveis/zap-juveve-goulin-66/07.webp" },
      { src: "/imoveis/zap-juveve-goulin-66/08.webp" },
      { src: "/imoveis/zap-juveve-goulin-66/09.webp" },
      { src: "/imoveis/zap-juveve-goulin-66/10.webp" },
    ],
    features: ["1 suíte", "Reformado", "Cozinha planejada", "Espaço gourmet", "SEM ELEVADOR (3º andar)"],
    description: "Reformado no Juvevê: 3 quartos sendo 1 suíte, sala em 2 ambientes integrada à cozinha com planejados, 1 vaga privativa. Condomínio com espaço gourmet, playground e bicicletário. 3º andar sem elevador. Sillos Imóveis.",
    source: "Zap Imóveis · Sillos Imóveis",
    zapId: "2909577516",
  },
  {
    id: "zap-cabral-manoel-104",
    title: "Apartamento com 3 Quartos - Cabral (andar alto)",
    neighborhood: "Cabral",
    address: "Rua Doutor Manoel Pedro, 470 ap. 1401 - Cabral, Curitiba - PR",
    area: 104,
    bedrooms: 3,
    bathrooms: 3,
    parking: 2,
    rent: 2950,
    condo: 1174,
    iptu: 288,
    total: 4412,
    phone: "",
    email: "",
    link: "https://www.zapimoveis.com.br/imovel/aluguel-apartamento-3-quartos-com-cozinha-cabral-curitiba-pr-104m2-id-2912447929/",
    image: "/imoveis/zap-cabral-manoel-104.webp",
    photos: [
      { src: "/imoveis/zap-cabral-manoel-104.webp", caption: "Foto principal" },
      { src: "/imoveis/zap-cabral-manoel-104/01.webp" },
      { src: "/imoveis/zap-cabral-manoel-104/02.webp" },
      { src: "/imoveis/zap-cabral-manoel-104/03.webp" },
      { src: "/imoveis/zap-cabral-manoel-104/04.webp" },
      { src: "/imoveis/zap-cabral-manoel-104/05.webp" },
      { src: "/imoveis/zap-cabral-manoel-104/06.webp" },
      { src: "/imoveis/zap-cabral-manoel-104/07.webp" },
      { src: "/imoveis/zap-cabral-manoel-104/08.webp" },
      { src: "/imoveis/zap-cabral-manoel-104/09.webp" },
      { src: "/imoveis/zap-cabral-manoel-104/10.webp" },
    ],
    features: ["1 suíte", "Todos com armários", "2 vagas", "Andar alto", "Portaria 24h"],
    description: "Andar alto com vista permanente: 3 quartos sendo 1 suíte (todos com armários), sala 2 ambientes com sacada, cozinha com armários, 2 vagas no subsolo. Salão de festas e churrasqueira, portaria 24h. Próximo ao Terminal do Cabral. AKG Imóveis.",
    source: "Zap Imóveis · AKG Imóveis",
    zapId: "2912447929",
  },
];

// --- VENDA (S001, snapshot 22/09/2026, Zap Imóveis, HTTP 200 via browser real).
// transaction: "venda"; total = salePrice (custo total efetivo de aquisição).
// rent: 0 (não se aplica); contato sempre pelo link (telefones mascarados).
// Fazendinha 80m² R$395k DESCARTADO: só 5 fotos (< 8 mínimas). Ecoville entrou no lugar.
export const saleApartments: Apartment[] = [
  {
    id: "zap-bacacheri-parana-107",
    title: "Apartamento com 3 Quartos à venda - Bacacheri",
    neighborhood: "Bacacheri",
    address: "Avenida Paraná - Bacacheri, Curitiba - PR",
    area: 107,
    bedrooms: 3,
    bathrooms: 3,
    parking: 2,
    rent: 0,
    condo: 1778,
    iptu: 1991,
    total: 800000,
    phone: "",
    email: "",
    link: "https://www.zapimoveis.com.br/imovel/venda-apartamento-3-quartos-com-playground-bacacheri-curitiba-pr-107m2-id-2903681824/",
    image: "/imoveis/zap-bacacheri-parana-107.webp",
    features: ["1 suíte", "Varanda", "Elevador", "Playground", "Interfone", "Escritório"],
    description: "3 quartos sendo 1 suíte, 107m² no Bacacheri (Av. Paraná). 3 banheiros, 2 vagas, varanda, elevador, playground, interfone e escritório. Condomínio R$1.778/mês, IPTU R$1.991. Hapen Imóveis. 25 fotos no anúncio — validar antes de visitar.",
    source: "Zap Imóveis · Hapen Imóveis",
    zapId: "2903681824",
    transaction: "venda",
    salePrice: 800000,
    photos: [
      { src: "/imoveis/zap-bacacheri-parana-107.webp", caption: "Foto principal" },
      { src: "/imoveis/zap-bacacheri-parana-107/01.webp" },
      { src: "/imoveis/zap-bacacheri-parana-107/02.webp" },
      { src: "/imoveis/zap-bacacheri-parana-107/03.webp" },
      { src: "/imoveis/zap-bacacheri-parana-107/04.webp" },
      { src: "/imoveis/zap-bacacheri-parana-107/05.webp" },
      { src: "/imoveis/zap-bacacheri-parana-107/06.webp" },
      { src: "/imoveis/zap-bacacheri-parana-107/07.webp" },
      { src: "/imoveis/zap-bacacheri-parana-107/08.webp" },
      { src: "/imoveis/zap-bacacheri-parana-107/09.webp" },
      { src: "/imoveis/zap-bacacheri-parana-107/10.webp" },
    ],
    verifiedAt: "2026-09-22",
  },
  {
    id: "zap-tingui-brasilio-71",
    title: "Apartamento com 3 Quartos à venda - Tingui",
    neighborhood: "Tingui",
    address: "Rua Brasílio Bacellar Filho - Tingui, Curitiba - PR",
    area: 71,
    bedrooms: 3,
    bathrooms: 1,
    parking: 1,
    rent: 0,
    condo: 550,
    iptu: 0,
    total: 354010,
    phone: "",
    email: "",
    link: "https://www.zapimoveis.com.br/imovel/venda-apartamento-3-quartos-tingui-curitiba-pr-71m2-id-2913009858/",
    image: "/imoveis/zap-tingui-brasilio-71.webp",
    features: ["Aceita animais", "71m²", "IPTU isento"],
    description: "3 quartos, 71m² no Tingui (Rua Brasílio Bacellar Filho). 1 banheiro, 1 vaga, aceita animais, IPTU isento. Condomínio R$550/mês. Corretor Lauzemar Adão Coelho de Andrade (CRECI 17067). Anúncio criado em 19/09/2026. 23 fotos no anúncio — validar antes de visitar.",
    source: "Zap Imóveis · Lauzemar Adão Coelho (CRECI 17067)",
    zapId: "2913009858",
    transaction: "venda",
    salePrice: 354010,
    photos: [
      { src: "/imoveis/zap-tingui-brasilio-71.webp", caption: "Foto principal" },
      { src: "/imoveis/zap-tingui-brasilio-71/01.webp" },
      { src: "/imoveis/zap-tingui-brasilio-71/02.webp" },
      { src: "/imoveis/zap-tingui-brasilio-71/03.webp" },
      { src: "/imoveis/zap-tingui-brasilio-71/04.webp" },
      { src: "/imoveis/zap-tingui-brasilio-71/05.webp" },
      { src: "/imoveis/zap-tingui-brasilio-71/06.webp" },
      { src: "/imoveis/zap-tingui-brasilio-71/07.webp" },
      { src: "/imoveis/zap-tingui-brasilio-71/08.webp" },
      { src: "/imoveis/zap-tingui-brasilio-71/09.webp" },
      { src: "/imoveis/zap-tingui-brasilio-71/10.webp" },
    ],
    verifiedAt: "2026-09-22",
  },
  {
    id: "zap-aguaverde-iguacu-140",
    title: "Apartamento com 3 Quartos à venda - Água Verde",
    neighborhood: "Água Verde",
    address: "Avenida Iguaçu - Água Verde, Curitiba - PR",
    area: 140,
    bedrooms: 3,
    bathrooms: 5,
    parking: 2,
    rent: 0,
    condo: 1300,
    iptu: 3580,
    total: 1395000,
    phone: "",
    email: "",
    link: "https://www.zapimoveis.com.br/imovel/venda-apartamento-3-quartos-com-academia-agua-verde-curitiba-pr-140m2-id-2912939346/",
    image: "/imoveis/zap-aguaverde-iguacu-140.webp",
    features: ["3 suítes", "9º andar com elevador", "Aceita animais", "Ótimo preço (Zap)"],
    description: "3 quartos sendo 3 suítes, 140m² na Água Verde (Av. Iguaçu). 5 banheiros, 2 vagas, 9º andar com elevador, aceita animais, academia no condomínio. Selo Ótimo preço do Zap. Condomínio R$1.300/mês, IPTU R$3.580. Sym Imóveis (Creci 06228-J-PR). Anúncio criado em 19/09/2026. 49 fotos no anúncio — validar antes de visitar.",
    source: "Zap Imóveis · Sym Imóveis",
    zapId: "2912939346",
    transaction: "venda",
    salePrice: 1395000,
    photos: [
      { src: "/imoveis/zap-aguaverde-iguacu-140.webp", caption: "Foto principal" },
      { src: "/imoveis/zap-aguaverde-iguacu-140/01.webp" },
      { src: "/imoveis/zap-aguaverde-iguacu-140/02.webp" },
      { src: "/imoveis/zap-aguaverde-iguacu-140/03.webp" },
      { src: "/imoveis/zap-aguaverde-iguacu-140/04.webp" },
      { src: "/imoveis/zap-aguaverde-iguacu-140/05.webp" },
      { src: "/imoveis/zap-aguaverde-iguacu-140/06.webp" },
      { src: "/imoveis/zap-aguaverde-iguacu-140/07.webp" },
      { src: "/imoveis/zap-aguaverde-iguacu-140/08.webp" },
      { src: "/imoveis/zap-aguaverde-iguacu-140/09.webp" },
      { src: "/imoveis/zap-aguaverde-iguacu-140/10.webp" },
    ],
    verifiedAt: "2026-09-22",
  },
  {
    id: "zap-capaoraso-churchill-78",
    title: "Apartamento com 3 Quartos à venda - Capão Raso",
    neighborhood: "Capão Raso",
    address: "Avenida Winston Churchill - Capão Raso, Curitiba - PR",
    area: 78,
    bedrooms: 3,
    bathrooms: 1,
    parking: 2,
    rent: 0,
    condo: 904,
    iptu: 191,
    total: 799000,
    phone: "",
    email: "",
    link: "https://www.zapimoveis.com.br/imovel/venda-apartamento-3-quartos-com-piscina-capao-raso-curitiba-pr-78m2-id-2913043342/",
    image: "/imoveis/zap-capaoraso-churchill-78.webp",
    features: ["1 suíte", "Varanda", "Piscina", "Cozinha"],
    description: "3 quartos sendo 1 suíte, 78m² no Capão Raso (Av. Winston Churchill). 1 banheiro, 2 vagas, varanda, piscina no condomínio. Condomínio R$904/mês, IPTU R$191. Cadena Imóveis - Vendas (Creci 06230-J-PR). Anúncio criado em 19/09/2026. 39 fotos no anúncio — validar antes de visitar.",
    source: "Zap Imóveis · Cadena Imóveis",
    zapId: "2913043342",
    transaction: "venda",
    salePrice: 799000,
    photos: [
      { src: "/imoveis/zap-capaoraso-churchill-78.webp", caption: "Foto principal" },
      { src: "/imoveis/zap-capaoraso-churchill-78/01.webp" },
      { src: "/imoveis/zap-capaoraso-churchill-78/02.webp" },
      { src: "/imoveis/zap-capaoraso-churchill-78/03.webp" },
      { src: "/imoveis/zap-capaoraso-churchill-78/04.webp" },
      { src: "/imoveis/zap-capaoraso-churchill-78/05.webp" },
      { src: "/imoveis/zap-capaoraso-churchill-78/06.webp" },
      { src: "/imoveis/zap-capaoraso-churchill-78/07.webp" },
      { src: "/imoveis/zap-capaoraso-churchill-78/08.webp" },
      { src: "/imoveis/zap-capaoraso-churchill-78/09.webp" },
      { src: "/imoveis/zap-capaoraso-churchill-78/10.webp" },
    ],
    verifiedAt: "2026-09-22",
  },
  {
    id: "zap-ecoville-rosa-87",
    title: "Apartamento com 3 Quartos à venda - Ecoville",
    neighborhood: "Ecoville",
    address: "Rua Rosa Kaint Nadolny - Ecoville, Curitiba - PR",
    area: 87,
    bedrooms: 3,
    bathrooms: 2,
    parking: 1,
    rent: 0,
    condo: 870,
    iptu: 87,
    total: 1317954,
    phone: "",
    email: "",
    link: "https://www.zapimoveis.com.br/imovel/venda-apartamento-3-quartos-com-piscina-ecoville-curitiba-pr-87m2-id-2895188181/",
    image: "/imoveis/zap-ecoville-rosa-87.webp",
    features: ["1 suíte", "Varanda gourmet", "Aceita animais", "Ar-condicionado", "Lareira", "Depósito"],
    description: "3 quartos sendo 1 suíte, 87m² no Ecoville (Rua Rosa Kaint Nadolny). 2 banheiros, 1 vaga, varanda gourmet, ar-condicionado, lareira, depósito, escritório, piscina no condomínio, aceita animais. Condomínio R$870/mês, IPTU R$87. L7 Imóveis (Creci 04131-J-PR). 65 fotos no anúncio — validar antes de visitar.",
    source: "Zap Imóveis · L7 Imóveis",
    zapId: "2895188181",
    transaction: "venda",
    salePrice: 1317954,
    photos: [
      { src: "/imoveis/zap-ecoville-rosa-87.webp", caption: "Foto principal" },
      { src: "/imoveis/zap-ecoville-rosa-87/01.webp" },
      { src: "/imoveis/zap-ecoville-rosa-87/02.webp" },
      { src: "/imoveis/zap-ecoville-rosa-87/03.webp" },
      { src: "/imoveis/zap-ecoville-rosa-87/04.webp" },
      { src: "/imoveis/zap-ecoville-rosa-87/05.webp" },
      { src: "/imoveis/zap-ecoville-rosa-87/06.webp" },
      { src: "/imoveis/zap-ecoville-rosa-87/07.webp" },
      { src: "/imoveis/zap-ecoville-rosa-87/08.webp" },
      { src: "/imoveis/zap-ecoville-rosa-87/09.webp" },
      { src: "/imoveis/zap-ecoville-rosa-87/10.webp" },
    ],
    verifiedAt: "2026-09-22",
  },
];
